### ISSUE TITLE
build failed whild use CocoaPods

### ISSUE THREAD

**Issue by qx** [bizz84/MVCarouselCollectionView#4]
/Users/ok/Downloads/testCollectionview/testCollectionview/ViewController.swift:12:36: Use of undeclared type 'MVCarouselCollectionView', what' wrong? @bizz84

**Comment by bizz84** [comment]
Apologies for the very late reply!

Because MVCarouselCollectionView is a Swift framework, it needs to be imported in the source files that use it. Can you try to add this at the top of your to your view controller?

``` swift
import MVCarouselCollectionView
```

I updated the usage section on the README file to make this clearer.
